[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
memecoin_prediction_market = "AJrErLEJXotf5ECiEHXqr89Qyn6huDzawT9PW6TmpW9e"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/pradip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
